[tool.poetry]
name = "packages"
version = "0.1.0"
description = ""
authors = ["Isciane Nicolle <isciane.nicolle@wishow.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
